### ISSUE TITLE
Use custom parameter with live server.

### ISSUE THREAD

**Issue by CallumNZ** [lekoala/bootstrap5-autocomplete#1]
From the docs:
`A ?query= parameter is passed along with the current value of the searchInput.`

This seems quite limiting. Can the name of the parameter be specified to match an existing API?

**Comment by lekoala** [comment]
@CallumNZ this can be easily tweaked by adding a new key to serverParams and use that instead of a fixed value

**Comment by CallumNZ** [comment]
Hi, thanks for the reply. Can you help me with `serverParams` ? I can't figure out how to do what I need. This is my config:

```
      Autocomplete.init("input.autocomplete", {
        valueField: "id",
        labelField: "title",
        highlightTyped: false,
        liveServer: true,
        server: "/suggest",
        noCache: false,
      });
```

When I type in the letter `t`, it makes the request: `http://localhost:8080/suggest?query=t`
I want the request to be:`http://localhost:8080/suggest?prefix=t`

**Comment by lekoala** [comment]
@CallumNZ I added the queryField parameter that will allow you to replace the default "query" parameter with prefix

**Comment by CallumNZ** [comment]
Thank you!!

**Comment by lekoala** [comment]
@CallumNZ 
by the way i've renamed this param to queryParam because it makes more sense in 1.1 sorry for this but I'd rather change it now than later

**Comment by CallumNZ** [comment]
No worries 😄
