### ISSUE TITLE
Style problem with input-group

### ISSUE THREAD

**Issue by ChaerilM** [lekoala/bootstrap5-autocomplete#12]
i'm having problem when using it along with input-group, 
```
<div class="input-group select-group">
  <span class="input-group-text bg-white border-end-0">
	<i class="fa-regular fa-location-pin text-black-50 fa-fw"></i>
  </span>
  <input class="form-control js-select-city" id="location" name="location" type="text" placeholder="Lokasi anda">
</div>
```

the placement was on top of the searchbox, instead of below it. so i added this to fix it. but the problem was `right:0` would only work if using `fullWidth: true`
```
.input-group {
  .autocomplete-menu {
    top: 100%;
    right: 0;
  }
}
```

pics:
![image](https://github.com/lekoala/bootstrap5-autocomplete/assets/1352081/c7ff55c8-eea3-4b59-80a8-9b908234e0a5)
![image](https://github.com/lekoala/bootstrap5-autocomplete/assets/1352081/7abc38a6-d53b-4519-b9a6-81f7bd8cd3fd)

**Comment by ChaerilM** [comment]
![image](https://github.com/lekoala/bootstrap5-autocomplete/assets/1352081/e290e2bb-9329-465b-a6bd-5e3e3aa19e4f)
@lekoala Thanks, I tried it earlier and it started off too far below, and when I scroll through the screen, the box goes up. for now, i'll stick with the non-fixed :)

**Comment by lekoala** [comment]
@ChaerilM do you have a jsfiddle or a codepen example that show this behaviour ? i don't have it in my demo.html :)

**Comment by lekoala** [comment]
@ChaerilM closing this, feel free to provide a jsfiddle or codepen with the actual issue if you need an update ;-)
