### ISSUE TITLE
Support HTML escape characters

### ISSUE THREAD

**Issue by hrkksm10** [lekoala/bootstrap5-autocomplete#13]
include HTML escape characters

        <datalist id="datalist">
          <option>abc&lt;br&gt;efg</option>
          <option>hij&lt;br&gt;klm</option>
        </datalist>

![image](https://github.com/lekoala/bootstrap5-autocomplete/assets/8214575/81d4e34d-30e6-4b26-9654-2b23c29830fc)

Click item
![image](https://github.com/lekoala/bootstrap5-autocomplete/assets/8214575/f24c6ea2-eef3-4c4f-a0d0-93837e1750bd)

**Comment by lekoala** [comment]
Done in https://github.com/lekoala/bootstrap5-autocomplete/releases/tag/1.1.9

**Comment by hrkksm10** [comment]
Thank you. good work!
