### ISSUE TITLE
Unable to pass arrays to data-server-params

### ISSUE THREAD

**Issue by guifsdev** [lekoala/bootstrap5-autocomplete#18]
I wrapped bootstrap5-autocomplete in a vuejs component to pass some filters to a query along with `data-server-params`:
```
    <autocomplete-input
      id="test"
      label="Test"
      max-chips="1"
      type="text"
      data-live-server
      data-server="/admin/search"
      data-server-method="post"
      :data-server-params="searchParams"
      data-label-field="name"
      data-value-field="id"
      placeholder="Test"
    />
```

In this template, `data-server-params` is asigned a computed property, which should resolve to this:
```
    searchParams() {
      const { item_type } = this.compound; //user input: starting value is null
      const foo = 'test'; //static... test
      const params = {
        resource: "composition",
        field: "searchable",
        filters: [
           ["item_type", "=", item_type], 
           ["item_type", "!=", foo], 
        ],
      };
      return JSON.stringify(params);
    },
```

The issue is that it's only accepting static values and won't use variables that may have been updated, like `item_type`. The above code will dump the following no matter the value of `item_type`:
`^ "item_type,=,,item_type,!=,test"`

I'm wondering if it's possible to achieve this.

Best regards.

**Comment by lekoala** [comment]
fair point i didn't plan these values to change dynamically

i guess for that specific one, it would make sense to read fresh values each time

i've just pushed an update to master you can give it a try ;-)

**Comment by lekoala** [comment]
published in https://github.com/lekoala/bootstrap5-autocomplete/releases/tag/1.1.16
seems to work fine from what i can tell

**Comment by guifsdev** [comment]
I'll check as soon as I get home. I appreciate you quick support once again!
