### ISSUE TITLE
Option to select different highlighting effects for highlightTyped

### ISSUE THREAD

**Issue by AgentSmith0** [lekoala/bootstrap5-autocomplete#22]
An option to select other highlighting styles would be nice to have. E.g. https://github.com/gch1p/bootstrap-5-autocomplete uses `highlightClass`, which allows highlighting with just changing the text color or making the text bolder using bootstrap classes.

**Comment by lekoala** [comment]
not sure this is very common use case. making text bolder will change the width, and changing text color makes it hard to work with contrast
if you really need this, you can easily apply custom styles to the mark tag yourself

**Comment by lekoala** [comment]
but why not since i'm working on it anyway
https://github.com/lekoala/bootstrap5-autocomplete/releases/tag/1.1.18

**Comment by lekoala** [comment]
@AgentSmith0 mark seems more semantically correct even though it serves no practical purpose. You probably reset its style anyway. and now that you can pass a class it's quite easy to add a p-0 if needed
is this a real issue?

**Comment by lekoala** [comment]
honestly i'm not even sure why someone would need this :) i would just style things in my global stylesheet instead of passing arguments but here you go https://github.com/lekoala/bootstrap5-autocomplete/releases/tag/1.1.21
