### ISSUE TITLE
Browser native autocomplete dialog showing up sometimes

### ISSUE THREAD

**Issue by AgentSmith0** [lekoala/bootstrap5-autocomplete#23]
Since the target input doesn't have `autocomplete="off"` set, because it overrides this attribute somehow, two autocomplete menus are showing up, which is not really wanted. Maybe an option to set `autocomplete="off"` could fix this issue.

**Comment by lekoala** [comment]
autocomplete off doesn't work in most situation
this is why i'm using a random string for it

**Comment by lekoala** [comment]
do you have an example and a given browser that show this issue?

**Comment by lekoala** [comment]
mhh that's odd, i was using "off" before but sometimes it was ignored by the browser. but it seems my method doesn't work any better so maybe better to stick with off. you can check on master

**Comment by lekoala** [comment]
@AgentSmith0 fyi i added a new option (the original reason why i didn't use autocomplete="off") for fields like city/addresses where browser native autocompletion may show up
https://github.com/lekoala/bootstrap5-autocomplete/releases/tag/1.1.20
