### ISSUE TITLE
How can I manipulate the object after selecting it?

### ISSUE THREAD

**Issue by bdusu1** [lekoala/bootstrap5-autocomplete#27]
Hi, 
very good class.  I can't find a way to capture what the class displays to the console when selecting a list item.

**Comment by lekoala** [comment]
using onSelectItem ?

**Comment by bdusu1** [comment]
Hi, thanks, but I've tried to capture that information but I can't find a way to use it with javascript when selecting it. it's here ?

this._config.onSelectItem(item, this);    //console.log(this);
      this.hideSuggestions();
      this._preventInput = false;

**Comment by lekoala** [comment]
check out demo.html maybe you can find something there :)

**Comment by bdusu1** [comment]
Here it is but I can't access the object.

const opts = {
      onSelectItem: console.log,

    };
console.log(opts.onSelectItem)

**Comment by lekoala** [comment]
not sure what is your issue

```
const opts = {
   onSelectItem: console.log,
};
new Autocomplete(this.el, opts);
```

this works fine

**Comment by lekoala** [comment]
closing this, feel free to reopen if you can provide a demo of the issue
