### ISSUE TITLE
activeClass doesn't override itemClass?

### ISSUE THREAD

**Issue by Taapo** [lekoala/bootstrap5-autocomplete#28]
When I use:

`itemClass: "text-muted",`

and then add:

`activeClass: ["bg-primary", "text-white"],`

The text inside bg-primary is still muted, not white ...

**Comment by lekoala** [comment]
that is expected, text-muted add this .text-muted {
    --bs-text-opacity: 1;
    color: var(--bs-secondary-color)!important;
} 
and therefore, it's not white

activeClass is added on top of the itemClass

**Comment by lekoala** [comment]
closing this, let me know if you need further help
