### ISSUE TITLE
Position issues

### ISSUE THREAD

**Issue by tonytomov** [lekoala/bootstrap5-autocomplete#3]
I try to use the component in some of my project and come across some problems:

Setting left position of the drop down according to the offsetLeft position of input in most contents gives unexpected result

This can be easy seen if you attach auto-complete to the following input

```
<div style="margin-left:200px;margin-top: 200px">
<table>
	<tr>
		<td> Please select </td>
		<td> <input id="test" type="text"/></td>
	</tr>
</table>
</div>
```

You will see the result.

My suggestion is to use parentOffset  and replace the leftOffset with parentOffset in _positionMenu()

```
 if (this._config.fullWidth) {
      // Use full input width
      this._dropElement.style.left = this._searchInput.offsetParent   + "px";
      this._dropElement.style.width = this._searchInput.offsetWidth + "px";
 } else {
      // Position next to search input
      let left = this._searchInput.offsetParent;
```

Another problem is when using the plugin in modal. The autocomplete is behind some html elements. 
To fix the issue I suggest you to set a fixed position of the dropdown..
In _configureDropElement(){..} you can add 

```
this._dropElement.style.position = "fixed";
...
```

Hope this helps

**Comment by lekoala** [comment]
@tonytomov hey thanks for your input
i didn't use fixed positioning because it comes with it's own set of issues (eg: when scrolling, you need to refresh position)
but your example is good, I added it to the demo and it now works fine (the solution is : don't set a left position!)

regarding the autocomplete being behind, this is probably just a z index issue no? it seems to work fine for me anyway in the demo but if you have an example i'm happy to provide a working solution

i pushed the changes on master, can you check if these work for you ?

**Comment by tonytomov** [comment]
@lekoala  Thank you very much. The position works as expected.

About the autocomplete being behind I have prepared a demo, which I copied from my content.
It is not a z-index. As can be seen the form has a z-index 950, while the autocomplete has z-index 1000.
The "problem" is that z-index has effect only on elements which have a property position

Look at the demo [here](autocomplete being behind) and you will see what I mean. The autocomplete is attached on the first (ID) field.

**Comment by lekoala** [comment]
@tonytomov ok, i see
I've added your example to the repo if you don't mind to test it more easily.
It's now working
Couple of side notes:
- don't init twice
- try to have a body with full height to allow positioning

**Comment by tonytomov** [comment]
You can check it [here](https://guriddo.net/demo/testcases/autocomplete/demo-jqueryui.html#)

As you can see setting browser height does not help.

**Comment by lekoala** [comment]
@tonytomov ah yes, that one is nasty
well, the main issue being the "overflow: hidden" on the jquery ui modal that serves no purpose :-)

but i guess you are right, there are some situations were fixed positioning is not avoidable. I added basic support for that (i tried with floating ui, but that adds a whole 7kb to the lib which is not reasonable :-) )

**Comment by lekoala** [comment]
if you can try on master and let me know :)

**Comment by tonytomov** [comment]
It is working fine for me.
Making fixed pos  as option is good solution.

Please take look on the other issue which i posted. ;-)

Thanks for quick support
