### ISSUE TITLE
Add hooks around fetch

### ISSUE THREAD

**Issue by xavfernandez** [lekoala/bootstrap5-autocomplete#30]
Currently `this._searchInput.classList.add(LOADING_CLASS)` is called before and `this._searchInput.classList.remove(LOADING_CLASS);` after.

I would like to perform more actions when the search starts & stops.
Two hooks `beforeFetch` / `afterFetch` (with `this._searchInput.classList` updates as the default behavior) would be perfect if it makes sense for your project.

In the meantime,
```
  const callback = (mutationList, _observer) => {
    for (const mutation of mutationList) {
        if (mutation.type === "attributes" && mutation.attributeName === "class") {
          if (mutation.target.classList.contains("is-loading")) {
              // search is happening 
          } else {
              // search has ended
          }
        }
    }
  }
  const observer = new MutationObserver(callback)
  observer.observe(searchInput, {attributes: true, childList: false, subtree: false});
```
fits the bill but is somewhat cumbersome...

Thanks for this library :)

**Comment by lekoala** [comment]
seems easy to add :-)
https://github.com/lekoala/bootstrap5-autocomplete/commit/7c5903c4f75ed96a542f14f6952e2d7638c1f715

do you need a promise or something in the beforeFetch hook?

**Comment by xavfernandez** [comment]
That was quick :)

> do you need a promise or something in the beforeFetch hook?

Not for my use case.
