### ISSUE TITLE
Re-bind to changed items list?

### ISSUE THREAD

**Issue by toby1kenobi** [lekoala/bootstrap5-autocomplete#32]
Great component, thanks for making! Is it possible to re-bind it to an updated list of items, if that list changes?

**Comment by toby1kenobi** [comment]
PS What I'd like to do is remove items from the list, once selected by a user

**Comment by lekoala** [comment]
there is a setData method that you can call
however if the goal is to hide the currently selected item, maybe that's worth a new config option, should be fairly easy to do

**Comment by lekoala** [comment]
exactly

**Comment by toby1kenobi** [comment]
Thanks
