### ISSUE TITLE
Feature idea: Optional Fill in button

### ISSUE THREAD

**Issue by AgentSmith0** [lekoala/bootstrap5-autocomplete#33]
What about adding an optional "Fill in" button next to each item in the autocomplete list, that just sets the input value without calling the selection callback.
Example:
![grafik](https://github.com/lekoala/bootstrap5-autocomplete/assets/67276662/3511278f-c8d1-49c2-a075-a846e1896d60)

**Comment by lekoala** [comment]
what would be the use case for this ?

**Comment by lekoala** [comment]
mhh i see. yes that makes a lot of sense. i have no spare time to implement this but if anyone wants to make a PR i would be happy to review it :)

**Comment by lekoala** [comment]
@AgentSmith0 it's pushed on master, it looks like this

<img width="409" alt="image" src="https://github.com/lekoala/bootstrap5-autocomplete/assets/250762/7b154a1a-a6cd-47da-8a13-13056508fefc">

**Comment by lekoala** [comment]
@AgentSmith0 pushed on master. indeed if you want to keep editing the focus should stay there
