### ISSUE TITLE
Fuzzy match accents etc

### ISSUE THREAD

**Issue by toby1kenobi** [lekoala/bootstrap5-autocomplete#37]
Is it possible to get the autocomplete to fuzzy match characters like u for ü, o for ó etc?

**Comment by lekoala** [comment]
that already seems to be the case but may be browser dependent

<img width="265" alt="image" src="https://github.com/lekoala/bootstrap5-autocomplete/assets/250762/684a117a-00b3-4ab8-abf3-adea49266e1a">

**Comment by toby1kenobi** [comment]
Thanks for getting back to me - I have it on [this site I made](https://artle.uk/), how does that behave for you? If I type "Miro" I do not see results for "Joan Miró", for example.

**Comment by lekoala** [comment]
aren't you using this       <script src="https://cdn.jsdelivr.net/npm/@tarekraafat/autocomplete.js@10.2.7/dist/autoComplete.min.js" defer></script> ??
which is not mine :-)

**Comment by toby1kenobi** [comment]
OMG, I completely am - what a moron (me)?! I'm *so* sorry for wasting your time. I did originally use yours, I cannot now remember why I switched.

Apologies, again
