### ISSUE TITLE
feature loading when waiting data from server-side

### ISSUE THREAD

**Issue by arezascarlet** [lekoala/bootstrap5-autocomplete#38]
i hope you can create feature loading when waiting data from server-side like option "notFoundMessage" and can be customize text or tag html

**Comment by lekoala** [comment]
hi there,
i'm not sure that showing a message is the best way to go. basically in the current state of things i need to wait for the results before displaying the dropdown
in the meantime i think it should be easy enough to use the loading class to show an animation or a loading icon when things are getting processed

**Comment by arezascarlet** [comment]
okey i'm understand your concept, can you give me example.
sorry,  I'm a beginner in web front end.
thanks

**Comment by lekoala** [comment]
in the demo.html there is already a blinking animation but if you want to add an icon something like this would do

https://github.com/lekoala/bootstrap5-autocomplete/commit/a1feee07c7d4241234802aa357b06f43936bf703
