### ISSUE TITLE
Autocomplete covers up input in BS5 with floating labels

### ISSUE THREAD

**Issue by eaglexboy** [lekoala/bootstrap5-autocomplete#39]
I was trying to use the autocompelte with live server option and works great. My problem is that the the dropdown created using the response is covering up the input in a input group

Before entering any value
![image](https://github.com/lekoala/bootstrap5-autocomplete/assets/9122907/b8dd8335-161f-45da-ba5a-06dd88e14017)

With autocomplete dropdown
![image](https://github.com/lekoala/bootstrap5-autocomplete/assets/9122907/630e6722-a3fb-4263-bffb-a5b1ef7f8a4b)

[Codepen Example](https://codepen.io/eaglexboy/pen/VwRbbbV)

Is there something I need to do that will move the Dropdown below the input like it does with a regular input?

**Comment by eaglexboy** [comment]
After looking into it further the issue appears to be from the BS CSS "position" attribute for .dropdown-menu in [_dropdown.scss](https://github.com/twbs/bootstrap/blob/main/scss/_dropdown.scss#L49)

I'm not got at css so I don't know what the fix would be but if you set position to relative it shows on the bottom but everything gets shifted.

[Codepen Example](https://codepen.io/eaglexboy/pen/poYPPZP)

**Comment by lekoala** [comment]
you could try using fixed positioning (see fixed option)

**Comment by eaglexboy** [comment]
I tried using fixed position and the result is the same

![image](https://github.com/lekoala/bootstrap5-autocomplete/assets/9122907/22dca26b-23f0-47b2-8dcb-929735ee63a5)

![image](https://github.com/lekoala/bootstrap5-autocomplete/assets/9122907/0e7d8665-dd02-4288-98a5-2c2ddc0e1417)

https://codepen.io/eaglexboy/pen/poYPPZP

**Comment by eaglexboy** [comment]
I tried it in [codepen](https://codepen.io/eaglexboy/pen/VwRzLxd) and it worked but when I tried it on my app it did not

![image](https://github.com/lekoala/bootstrap5-autocomplete/assets/9122907/5c041795-aea9-4eb7-a51c-dd7bda10ebfd)
