### ISSUE TITLE
Add support for custom server error response handlers

### ISSUE THREAD

**Issue by dabico** [lekoala/bootstrap5-autocomplete#45]
I started integrating this library into my projects (phenomenal work by the way), but I noticed that there is no way of specifying custom error handlers when `fetch` fails:

https://github.com/lekoala/bootstrap5-autocomplete/blob/a1feee07c7d4241234802aa357b06f43936bf703/autocomplete.js#L1236-L1242

It would be nice if we had an error-handling equivalent to `onServerResponse` (i.e. `onServerUnreachable` or `onFailedFetch`), as `onAfterFetch` does not provide access to the returned `Promise`.

**Comment by dabico** [comment]
Wonderful! Patiently waiting for the next release 😄

**Comment by lekoala** [comment]
done :)
