### ISSUE TITLE
Bug: Option gets selected by mouse cursor position, not current item

### ISSUE THREAD

**Issue by AgentSmith0** [lekoala/bootstrap5-autocomplete#48]
If you use the arrow keys to select an item from the dropdown and click enter, the option won't get selected. Instead, the option under the mouse cursor position gets selected. This is a weird behavior...

**Comment by lekoala** [comment]
i'm not sure i get the issue,

this is what i have, it's selecting properly the highlighted option if i press enter


https://github.com/lekoala/bootstrap5-autocomplete/assets/250762/7bd03011-8c76-42c0-aec6-38692f64d137

**Comment by lekoala** [comment]
mhh yes, but i don't see how it could be otherwise. when you use the keyboard, that's what define the focus. if you move the mouse, it's going to select whatever you are hovering. You need to move it enough that it goes to another option to get the focus, so that's not a "small" move, it's already big enough to select another item.

do you know of any other library that does thing differently ? :-) i'm open to suggestions but i'd like to see how that's handled in other projects

**Comment by lekoala** [comment]
mhh i see yes

i don't know if i'm super happy with the fact it can mean you have two items highlighted 

for example three and five but i see what you mean
![image](https://github.com/lekoala/bootstrap5-autocomplete/assets/250762/fbc85c64-772e-4dbf-a84b-acfb48cdef57)

**Comment by lekoala** [comment]
soo.... decoupling the focus/selection is not always great

for example, i can hover things with the mouse, but then it's not "selected". this means, when using the keyboard, the navigation will start from the top (the first option). This also means that after using the keyboard, if I scroll down, i see the option hovered, but I have no idea anymore what's really selected and pressing enter will lead to the last selected entry...

I'm not sure that's great either, and honestly, I don't expect anyone to use the keyboard to select something, THEN move the mouse, AND expecting the input to keep track of whatever was keyboard selected

example below

https://github.com/lekoala/bootstrap5-autocomplete/assets/250762/c79a9dd0-bfd9-49b7-9db0-43374ebe4a4f

unless you have a very good reasoning against this, i'm not going forward with this

**Comment by lekoala** [comment]
that seems reasonable :) 

https://github.com/lekoala/bootstrap5-autocomplete/commit/5563882f6beb1af2e6675de8e08a7d69aab6af3f

can you give it a try?

**Comment by lekoala** [comment]
and published ;-)

**Comment by lekoala** [comment]
i'm going to close this for now feel free to reopen if you see a better way to handle this that covers all use cases
