### ISSUE TITLE
notFoundMessage is never displayed when using server

### ISSUE THREAD

**Issue by benwallis** [lekoala/bootstrap5-autocomplete#5]
When using the server option, the notFoundMessage is not displayed when there are no matches:

It can be fixed by adding following code after line 640:
https://github.com/lekoala/bootstrap5-autocomplete/blob/master/autocomplete.js#L640
```
this._dropElement.classList.add("show");
this._searchInput.ariaExpanded = "true";
this._positionMenu();
```

Also had to add positionMenu call there otherwise the width is not 100% when using fullWidth config option.

**Comment by lekoala** [comment]
@benwallis  good catch, fixed in https://github.com/lekoala/bootstrap5-autocomplete/releases/tag/1.1.2
