### ISSUE TITLE
Missing activeClasses

### ISSUE THREAD

**Issue by martin-lbe** [lekoala/bootstrap5-autocomplete#53]
First time moving the mouse over an item the activeClasses and is-active is missing

**Comment by lekoala** [comment]
this is very odd, have you an example for this ? 

you can see on the demo.html that any of them do get the blue background and the white text

except if for some reason it's not selecting the first item, in which case indeed there won't be any active classes on the first item until your properly select it

**Comment by martin-lbe** [comment]
Tried to record a video of what I am experiencing.

https://github.com/user-attachments/assets/5a5a30f8-52fd-4568-a41b-8ecef84eff53

**Comment by lekoala** [comment]
thanks that was super helpful !
there was an event listener missing for this case indeed!

fixed in https://github.com/lekoala/bootstrap5-autocomplete/releases/tag/1.1.33

**Comment by lekoala** [comment]
closing this, feel free to reopen if needed
