### ISSUE TITLE
onBeforeFetch should be able to change serverParams but it is called to late

### ISSUE THREAD

**Issue by hrvoj3e** [lekoala/bootstrap5-autocomplete#55]
I have a suggestion and will make a PR.

It makes more sense to call `onBeforeFetch()` [here](https://github.com/lekoala/bootstrap5-autocomplete/blob/ce698b9f6f615982dfaa7463fee280747041671e/autocomplete.js#L1243) at the begining of the `_loadFromServer()`  rather than [before](https://github.com/lekoala/bootstrap5-autocomplete/blob/ce698b9f6f615982dfaa7463fee280747041671e/autocomplete.js#L1286C38-L1287C1) explicit `fetch()`

__NOTE : It works after the first request but NOT the first time.__
  - if `onBeforeFetch()` was called earlier that would not be a problem

## Why?

Because `fetchOptions` can be dynamically updated before fetch is executed.

```js

Autocomplete.init('input.ein-suggest', {
    server: setting.server,
    serverMethod: 'POST',
    liveServer: true,
    noCache: true,
    debounceTime: 500,
    notFoundMessage: 'No results ...',
    serverParams: { scope: setting.scope },
    queryParam: 'suggest',
    valueField: 'value',
    labelField: 'title',
    highlightTyped: true,
    startsWith: true,
    preventBrowserAutocomplete: true,
    fillIn: true,
    onSelectItem: console.log,
    
    // I want to dynamically change serverParams for fetch() to use 
    onBeforeFetch: (ac) => {
        let cfg = ac.getConfig('serverParams');
        cfg.field = ac.getInput().getAttribute('data-field-name');
        ac.setConfig('serverParams', cfg);
    },

});
```

**Comment by lekoala** [comment]
thanks!
https://github.com/lekoala/bootstrap5-autocomplete/releases/tag/1.1.34
