### ISSUE TITLE
[ Enhancement ] Headers/dividers support

### ISSUE THREAD

**Issue by benwallis** [lekoala/bootstrap5-autocomplete#7]
Thanks for the recent update!

This is just a request/suggestion - it would be great if there was a way to utilise headers and/or dividers:

https://getbootstrap.com/docs/5.3/components/dropdowns/#headers
https://getbootstrap.com/docs/5.3/components/dropdowns/#dividers

Could be a config option such as "grouped" : true that expects the source data format to be an array of groups
```
[
    {
        "group": "My Group",
        "items": [
            {
                "itemValue" : "itemLabel",
            }
        ]
    },
    {
        "group": "Another Group",
        "items": [
            {
                "itemValue" : "itemLabel",
            }
        ]
    },
    {
        "itemValue" : "itemLabel",
    }
]
```

For dividers, maybe an item with empty string for label and value becomes a divider?

**Comment by lekoala** [comment]
why not :-) i don't exactly have time outside maintenance of the project itself, but if you feel like it, a PR is welcome ;-)

**Comment by benwallis** [comment]
Thanks, I will try to do so

**Comment by lekoala** [comment]
@benwallis fyi i'm working on this on my tags library 
https://github.com/lekoala/bootstrap5-tags/commit/ffa6f21486f309990a544fc0c378e720b1932690

it's not going to support dividers i think because it doesn't make sense for a select field, but i think your proposal would be easy enough to implement anyway, it's just a simple if in the render loop

**Comment by lekoala** [comment]
groups added in 1.1.13
i won't add dividers because they don't work will with filtering
i think you can do it yourself with render callbacks if needed
