### ISSUE TITLE
[ Enhancement ]  fetch parameters.

### ISSUE THREAD

**Issue by tonytomov** [lekoala/bootstrap5-autocomplete#8]
This is just suggestion - It will be good if we have a setting for the fetch request. Some sites does not accept method GET and only post. Moreover we can configure the cache option to preserve repeated request to the server. Other [useful options](https://developer.mozilla.org/en-US/docs/Web/API/fetch#syntax) can be set too 

Currently only **signal** is set exclusively .

**Comment by lekoala** [comment]
yes that makes a lot of sense

added in https://github.com/lekoala/bootstrap5-autocomplete/releases/tag/1.1.4
